import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Welcome",
    },
    {
      type: 'category',
      label: 'Cloud',
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "cloud/getting-started",
          label: "Getting Started",
        },
        {
          type: "doc",
          id: "cloud/chrome-devtools-protocol",
          label: "Chrome DevTools Protocol (CDP)",
        },
        {
          type: "category",
          label: "REST API",
          link: {
            type: "generated-index",
            title: "Cloud API",
            description: "Explore our API endpoints",
            slug: "/cloud/api",
          },
          items: require("./docs/cloud/api/sidebar.ts"),
          collapsed: false,
        },
        {
          type: "doc",
          id: "cloud/proxy",
          label: "Proxy",
        },
      ]
    },
    {
      type: "category",
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials'
        },
      ]
    }
  ],
};

export default sidebars;
